root = '.'

[build]
cmd = 'go build -o ./tmp/main.exe .'
bin = './tmp/main.exe'
delay = 500

[process]
start_port = 53700

[proxy]
port = 8099

[watch]
include = ['./']
exclude = ['vendor', '.git', 'tmp', 'node_modules']
extensions = ['go', 'html', 'tmpl']

[log]
level = 'info'
color = true
